### PR TITLE
Rescheduling, Adherence, and AddParticipant Tools

### PR DESCRIPTION
**Pull request by dephillipsmichael**
For a full description of the tool's requirements, see https://sagebionetworks.jira.com/browse/DIAN-186

This re-scheduling tool will be used by Ann to edit a user's study burst schedule.  It is not going to be called from the DataMigration class and will not effect data migration.  

@brucehoff you do not need to spend too much time on this review, as this will only be used to change schedules for participants in HASD and EXR, not to change schedules in the GCP DIAN observational trials or TU app.

However, I did try to include the same unit testing coverage standards that exist in the rest of the codebase.

### CODE REVIEW

**Review by brucehoff — COMMENTED** [review]
I'm sorry but this seems like logic that would be best reviewed by someone from the Bridge team.  I'll add Alx as a reviewer but you can change that if you feel there's someone better, @dephillipsmichael .

**Review by brucehoff — DISMISSED** [review]
I commented that, "is outside of my realm of understanding.  I don’t know anything about “schedules” or “burst cycles”. Would it be better to have a Bridge engineer review it?" to which @dephillipsmichael responded, " that's a reasonable conclusion on your part.  However the schedule data model is completely unique to the DIAN project so a bridge engineer would not be familiar either. As there are sufficient unit tests, and I've used the rescheduling program on 10-15 participants in the non-gcp study so far, I'd say we are safe to merge it without a more detailed review."

**Review by brucehoff — COMMENTED** [review]
The PR seems to change the purpose of the repo’, which was that of an automated data pipeline to add a set of manual data management tools.  Can I suggest that you work directly with the project managers on the tools you are building to support them?  They can confirm that the functionality and instructions are correct and meet their needs. It might be cleanest to create these tools in another Github repo’, for which they review the PRs.

**Comment by dephillipsmichael** [comment]
Closing, but keeping repo branch 'Tools' around.

**Pull request closed without merging**
